### ISSUE TITLE
Issues with 1.3.0 release

### ISSUE THREAD

**Issue by clburlison** [macmule/AutoImagrNBI#17]
The app itself is fine, most of these are cosmetics. The markdown in the release notes are a bit wonky: one 404 URL, wording is off on the version checking sentence, and your bullet points need a space for proper markdown rendering. 

Because you're busy and everyone likes to copy and paste:

``` raw
AutoImagrNBI now supports 10.11. Please see this post for more info: [AutoImagrNBI, AutoImagrNBI & El Capitan](https://macmule.com/2015/10/02/autocaspernbi-autoimagrnbi-el-capitan/)

NOTE: AutoImagrNBI will check the version of Imagr.app against latest release or it can download the latest release for you. Thanks to @clburlison for logging the enhancement & helping implement #2. For more information see: https://macmule.com/projects/autoimagrnbi/#Imagrapp

Other fixes included are:
* Move Imagr URL check to after adding OS.dmg & Imagr.app #16
* 10.11: Deleting dockfixup error #15
* 10.11: Error Copying booter.efi #14
* 10.11: Error Writing NBImageInfo.plist #13
* 10.11: SIP enabled #12
* Imagr slow to launch on 10.10 #11
```

Also, 1.3.0 is released as c61ad45 however you've made three commits since then (specifically the Sparkle fix) 0ad553e. Easiest way to correct this is just delete current 1.3.0 release and recreate with proper commit (unless Github has a way to change the release commit...however I don't believe that is the case). 

Cheers, Clayton

**Comment by clburlison** [comment]
Right so the easiest solution is 
1) Delete GH release 1.3.0
2) Delete git tag using `git tag -d '1.3.0'`
3) Push tags to Github `git push origin --tags`

Recreate Release using GH. 

Other solutions...don't worry about it as it's only three commits and might not be worth the effort.

This really goes against what git wants you to do but this project is small enough that it won't affect anyone.

**Comment by grahamgilbert** [comment]
Or just go with 1.3.1...

**Comment by macmule** [comment]
Yep.. I think i'll leave as-is & will tidy up when 1.3.1 comes out. 

If this affects anyone, it'll only be the crazies whom compile themselves :)

Thanks gents!
