### ISSUE TITLE
Mentions of 'Casper' (Gasp!) in some tooltips

### ISSUE THREAD

**Issue by Daz-wallace** [macmule/AutoImagrNBI#19]
Some areas of AutoImgrNBI mention Casper, presumably from the fork from AutoCasperNBI.

Found the items as follows in v1.3.0:
"Options" Button
-  "Always Set" Tab
  -  "Creates a minimal Dock..." - Mentions "Casper" instead of "Imagr" in the tool tip
  -  "Copies Imagr to NBI's Application's folder" - Mentions "Casper" instead of "Imagr" in the tool tip
  -  "Launches Imagr at Login" - Mentions "Casper" instead of "Imagr" in the tool tip
  -  "Removes Imagr's Quarantine Flag" - Mentions "Casper" instead of "Imagr" in the tool tip
-  "Standard" Tab
  -  Netboot - "Reduce Image Size" - Mentions "Casper" instead of "Imagr" in the tool tip
  -  Screen Sharing - VNC - "Passwords are saved in AutoCasperNBI's" - Wrong name and seems to end mid-sentence

Thanks for another awesome tool!

Darren

**Comment by macmule** [comment]
In 1.3.3
