### ISSUE TITLE
Add reporturl option to App config file.

### ISSUE THREAD

**Issue by sheagcraig** [macmule/AutoImagrNBI#21]
The application config at `/private/var/root/Library/Preferences/com.grahamgilbert.Imagr.plist` can now take a `reporturl` key which will configure Imagr to report to that server. See: 
https://github.com/grahamgilbert/imagr/wiki/Reporting

**Comment by sheagcraig** [comment]
Sorry-I don't know _any_ applescript; otherwise I'd just PR this for you.

**Comment by macmule** [comment]
Please test: https://github.com/macmule/AutoImagrNBI/releases/tag/1.3.4

There's a new "App Config" tab in the options window.

<img width="476" alt="screenshot 2016-09-11 21 39 13" src="https://cloud.githubusercontent.com/assets/2464974/18420488/a0bcea00-786b-11e6-82d8-dc442a76267d.png">

**Comment by macmule** [comment]
In 1.3.4
