### ISSUE TITLE
LoginLog.app and /Library/LaunchDaemons/com.grahamgilbert.first-boot-pkg.plist.

### ISSUE THREAD

**Issue by tungates** [macmule/AutoImagrNBI#23]
Hi,

I have currently been testing out Imagr 1.0.3 in VMFusion 8 . I've built the nbi with AutoImagrNBI and imaged the vm with a clean 10.11 image and there was a package to install the latest munki tools and run the bootstrap at first boot.
When the machine reboots it loads the login log.app but the first boot
is not running. Permissions on the launchdaemon file are: unknown
read/write, unknown read, everyone read.

The only way we have been able to get this to work is to untick the
Ignore Volume Ownership and check that root has the rights on the
file.

**Comment by macmule** [comment]
@tungates not able to recreate this.

Still having the issue?

**Comment by macmule** [comment]
FWIW, @pudquick has seen this.. & is looking to do a PR to fix within Imagr

**Comment by tungates** [comment]
Hi Ben,

I haven't tested this recently but i can give it a go if i have some time
this week.

Shane

**Comment by macmule** [comment]
Any update?

**Comment by tungates** [comment]
Hi Ben,

I'll give this a test today and let you know

**Comment by tungates** [comment]
Hi Ben,

I've just tested this out and all looks good now. No issues
