### ISSUE TITLE
Validation on file:/// paths

### ISSUE THREAD

**Issue by clburlison** [macmule/AutoImagrNBI#40]
Found by `@thehill` on Slack https://macadmins.slack.com/archives/imagr/p1487072613003150.

validateplist doesn't support `file:///` paths, so you should strip the `file://` and pass the native path to the plist. With that said I think that's going to hit another error of relative/absolute paths. My recommendation would be to check for file:/// path and simple WARN that the admin should verify manually.

![screen shot 2017-02-14 at 8 44 52 am](https://cloud.githubusercontent.com/assets/2831320/22934067/419e25c8-f293-11e6-92ef-58039a8b4504.png)

**Comment by macmule** [comment]
Taken the route of rejecting local config.plists & showing this message:
<img width="532" alt="screenshot 2017-09-07 22 03 25" src="https://user-images.githubusercontent.com/2464974/30186614-317774f6-941e-11e7-802d-035e865bbd34.png">
