### ISSUE TITLE
Cannot read OS Version if existing Preboot volume present

### ISSUE THREAD

**Issue by patgmac** [macmule/AutoImagrNBI#53]
`Tue May 29 12:23:18 EDT 2018 AutoCasperNBI 1.4.1
Tue May 29 12:23:19 EDT 2018 Running on OS 10.13.5 (17F70a)
Tue May 29 12:23:19 EDT 2018 Launched by username
Tue May 29 12:23:19 EDT 2018 UUID A32E610E-E7F3-40AB-81F7-0406A1E4B533
Tue May 29 12:23:19 EDT 2018 NetBoot is to be hosted on a single server.
Tue May 29 12:23:27 EDT 2018 Path: /Users/username/Downloads/osx_updated_180425-10.13.4-17E199.apfs.dmg
Tue May 29 12:23:27 EDT 2018 Trying to mount: /Users/username/Downloads/osx_updated_180425-10.13.4-17E199.apfs.dmg
Tue May 29 12:23:28 EDT 2018 Mounted to: /Volumes/Preboot 2
Tue May 29 12:23:28 EDT 2018 Cannot read OS Version`

Per the mighty Mule, the problem lies in https://github.com/macmule/AutoCasperNBI/blob/136c6aa071e3473b53cb2eb88a5331f4ce3f390f/AutoCasperNBI/AutoCasperNBIAppDelegate.applescript#L527

**Comment by macmule** [comment]
In 1.5.0
