### ISSUE TITLE
Error When building NBI from Mojave 10.14.1

### ISSUE THREAD

**Issue by aqueries** [macmule/AutoImagrNBI#57]
Unable to complete a build using Mojave InstallESD.dmg

Build fails when attempting to disable software update.

See screenshot and Logfile attatched

[Log.log](https://github.com/macmule/AutoImagrNBI/files/2614074/Log.log)

![screen shot 2018-11-26 at 2 29 06 pm](https://user-images.githubusercontent.com/7801232/48993185-fcdcae00-f187-11e8-98e7-e1f4da01c77f.png)

**Comment by aqueries** [comment]
forgot to mention, The build was attempted on a Mojave 10.14.1 Machine

**Comment by macmule** [comment]
@aqueries, you need an OS.dmg created with the likes of [AutoDMG](https://github.com/MagerValp/AutoDMG).. then use that.

Not the installESD.dmg you mentioned in your 1st post.

**Comment by macmule** [comment]
Closing this one off..
