### ISSUE TITLE
Catalina claims there is no space

### ISSUE THREAD

**Issue by gizmomo** [macmule/AutoImagrNBI#60]
Attempting to create an image while running Catalina. When I clicked Build, the error states I need 15GB but have zero. The local system had over 500GB free space. 

When I tried to save to an external HD I got caught in a loop claiming the folder already existed - _do I want to delete or use the existing_? Either option returns to the same choice dialog.

I switched to a 10.13 system and it worked like a charm.

I don't really need to run this from Catalina but thought you should know.

**Comment by macmule** [comment]
Thanks, Catalina is not supported & AutoImagrNBI will be put out to pasture soon.
